server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ProductDB
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: 64461f01e1af406da538b9c48d801ce59142452199ff112fb5404c8e7e98e3ff
  expiration: 86400000  # 24시간
  header: Authorization
  prefix: "Bearer "

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG

minio:
  endpoint: http://localhost:9000/
  accessKey: obDCGyvQjs8zPSBW7Bpd
  secretKey: wVLkHJ04z4hyj7xxhk4ksEyRDsdyEPOnNZWImsI8
  bucket: dev-test
